#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
#set -x

exitstatus=0
git ls-files --modified --exclude-standard ':/**/app.config' |
while read -r f
do
	if grep -q "<nlog>" "$f"
	then
		printf 'Please remove the nlog-block in file %s!\n' "$f"
		exitstatus=1
	else
		printf 'NLog not found in %s.\n' "$f"
	fi
done

exit "$exitstatus"
