#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
#set -x

List=$(git status | findstr modified | findstr app.config | cut -d ":" -f2 | xargs)
exitstatus=0

for f in "$List"
do
	if [ ${#f} -ge 1 ] 
	then 
		if grep -Rq "<nlog>" $f
		then
			printf "Please remove the nlog-block in file $f!"
			exitstatus=1
		else
			printf "NLog not found in $f."
		fi
	else
		printf "Variable is empty"
	fi
done

exit $exitstatus


