//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chummer.OmaeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dndjunkie.com/", ConfigurationName="OmaeService.omaeSoap")]
    public interface omaeSoap {
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/RegisterUser", ReplyAction="*")]
        Chummer.OmaeService.RegisterUserResponse RegisterUser(Chummer.OmaeService.RegisterUserRequest request);
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/Login", ReplyAction="*")]
        Chummer.OmaeService.LoginResponse Login(Chummer.OmaeService.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/SetEmailAddress", ReplyAction="*")]
        Chummer.OmaeService.SetEmailAddressResponse SetEmailAddress(Chummer.OmaeService.SetEmailAddressRequest request);
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/GetEmailAddress", ReplyAction="*")]
        Chummer.OmaeService.GetEmailAddressResponse GetEmailAddress(Chummer.OmaeService.GetEmailAddressRequest request);
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/ResetPassword", ReplyAction="*")]
        Chummer.OmaeService.ResetPasswordResponse ResetPassword(Chummer.OmaeService.ResetPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name GetCharacterTypesResult from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/GetCharacterTypes", ReplyAction="*")]
        Chummer.OmaeService.GetCharacterTypesResponse GetCharacterTypes(Chummer.OmaeService.GetCharacterTypesRequest request);
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/UploadCharacter", ReplyAction="*")]
        Chummer.OmaeService.UploadCharacterResponse UploadCharacter(Chummer.OmaeService.UploadCharacterRequest request);
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/UploadCharacter153", ReplyAction="*")]
        Chummer.OmaeService.UploadCharacter153Response UploadCharacter153(Chummer.OmaeService.UploadCharacter153Request request);
        
        // CODEGEN: Generating message contract since element name DownloadCharacterResult from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/DownloadCharacter", ReplyAction="*")]
        Chummer.OmaeService.DownloadCharacterResponse DownloadCharacter(Chummer.OmaeService.DownloadCharacterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/DeleteCharacter", ReplyAction="*")]
        bool DeleteCharacter(int intCharacterID);
        
        // CODEGEN: Generating message contract since element name strMetatype from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/FetchCharacters", ReplyAction="*")]
        Chummer.OmaeService.FetchCharactersResponse FetchCharacters(Chummer.OmaeService.FetchCharactersRequest request);
        
        // CODEGEN: Generating message contract since element name strMetatype from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/FetchCharacters153", ReplyAction="*")]
        Chummer.OmaeService.FetchCharacters153Response FetchCharacters153(Chummer.OmaeService.FetchCharacters153Request request);
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/UploadDataFile", ReplyAction="*")]
        Chummer.OmaeService.UploadDataFileResponse UploadDataFile(Chummer.OmaeService.UploadDataFileRequest request);
        
        // CODEGEN: Generating message contract since element name DownloadDataFileResult from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/DownloadDataFile", ReplyAction="*")]
        Chummer.OmaeService.DownloadDataFileResponse DownloadDataFile(Chummer.OmaeService.DownloadDataFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/DeleteDataFile", ReplyAction="*")]
        bool DeleteDataFile(int intDataID);
        
        // CODEGEN: Generating message contract since element name strFilesIncluded from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/FetchDataFiles", ReplyAction="*")]
        Chummer.OmaeService.FetchDataFilesResponse FetchDataFiles(Chummer.OmaeService.FetchDataFilesRequest request);
        
        // CODEGEN: Generating message contract since element name strUserName from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/UploadSheet", ReplyAction="*")]
        Chummer.OmaeService.UploadSheetResponse UploadSheet(Chummer.OmaeService.UploadSheetRequest request);
        
        // CODEGEN: Generating message contract since element name DownloadSheetResult from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/DownloadSheet", ReplyAction="*")]
        Chummer.OmaeService.DownloadSheetResponse DownloadSheet(Chummer.OmaeService.DownloadSheetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/DeleteSheet", ReplyAction="*")]
        bool DeleteSheet(int intSheetID);
        
        // CODEGEN: Generating message contract since element name strUser from namespace http://www.dndjunkie.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.dndjunkie.com/FetchSheets", ReplyAction="*")]
        Chummer.OmaeService.FetchSheetsResponse FetchSheets(Chummer.OmaeService.FetchSheetsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUser", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.RegisterUserRequestBody Body;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(Chummer.OmaeService.RegisterUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class RegisterUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        public RegisterUserRequestBody() {
        }
        
        public RegisterUserRequestBody(string strUserName, string strPassword) {
            this.strUserName = strUserName;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUserResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.RegisterUserResponseBody Body;
        
        public RegisterUserResponse() {
        }
        
        public RegisterUserResponse(Chummer.OmaeService.RegisterUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class RegisterUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RegisterUserResult;
        
        public RegisterUserResponseBody() {
        }
        
        public RegisterUserResponseBody(int RegisterUserResult) {
            this.RegisterUserResult = RegisterUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Chummer.OmaeService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string strUserName, string strPassword) {
            this.strUserName = strUserName;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Chummer.OmaeService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetEmailAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetEmailAddress", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.SetEmailAddressRequestBody Body;
        
        public SetEmailAddressRequest() {
        }
        
        public SetEmailAddressRequest(Chummer.OmaeService.SetEmailAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class SetEmailAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strEmail;
        
        public SetEmailAddressRequestBody() {
        }
        
        public SetEmailAddressRequestBody(string strUserName, string strEmail) {
            this.strUserName = strUserName;
            this.strEmail = strEmail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetEmailAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetEmailAddressResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.SetEmailAddressResponseBody Body;
        
        public SetEmailAddressResponse() {
        }
        
        public SetEmailAddressResponse(Chummer.OmaeService.SetEmailAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class SetEmailAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SetEmailAddressResult;
        
        public SetEmailAddressResponseBody() {
        }
        
        public SetEmailAddressResponseBody(bool SetEmailAddressResult) {
            this.SetEmailAddressResult = SetEmailAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmailAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmailAddress", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.GetEmailAddressRequestBody Body;
        
        public GetEmailAddressRequest() {
        }
        
        public GetEmailAddressRequest(Chummer.OmaeService.GetEmailAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class GetEmailAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        public GetEmailAddressRequestBody() {
        }
        
        public GetEmailAddressRequestBody(string strUserName) {
            this.strUserName = strUserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmailAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmailAddressResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.GetEmailAddressResponseBody Body;
        
        public GetEmailAddressResponse() {
        }
        
        public GetEmailAddressResponse(Chummer.OmaeService.GetEmailAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class GetEmailAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEmailAddressResult;
        
        public GetEmailAddressResponseBody() {
        }
        
        public GetEmailAddressResponseBody(string GetEmailAddressResult) {
            this.GetEmailAddressResult = GetEmailAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetPassword", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.ResetPasswordRequestBody Body;
        
        public ResetPasswordRequest() {
        }
        
        public ResetPasswordRequest(Chummer.OmaeService.ResetPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class ResetPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        public ResetPasswordRequestBody() {
        }
        
        public ResetPasswordRequestBody(string strUserName) {
            this.strUserName = strUserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResetPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResetPasswordResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.ResetPasswordResponseBody Body;
        
        public ResetPasswordResponse() {
        }
        
        public ResetPasswordResponse(Chummer.OmaeService.ResetPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class ResetPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ResetPasswordResult;
        
        public ResetPasswordResponseBody() {
        }
        
        public ResetPasswordResponseBody(bool ResetPasswordResult) {
            this.ResetPasswordResult = ResetPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCharacterTypesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCharacterTypes", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.GetCharacterTypesRequestBody Body;
        
        public GetCharacterTypesRequest() {
        }
        
        public GetCharacterTypesRequest(Chummer.OmaeService.GetCharacterTypesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCharacterTypesRequestBody {
        
        public GetCharacterTypesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCharacterTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCharacterTypesResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.GetCharacterTypesResponseBody Body;
        
        public GetCharacterTypesResponse() {
        }
        
        public GetCharacterTypesResponse(Chummer.OmaeService.GetCharacterTypesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class GetCharacterTypesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetCharacterTypesResult;
        
        public GetCharacterTypesResponseBody() {
        }
        
        public GetCharacterTypesResponseBody(System.Xml.Linq.XElement GetCharacterTypesResult) {
            this.GetCharacterTypesResult = GetCharacterTypesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadCharacterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadCharacter", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.UploadCharacterRequestBody Body;
        
        public UploadCharacterRequest() {
        }
        
        public UploadCharacterRequest(Chummer.OmaeService.UploadCharacterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class UploadCharacterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int intCharacterID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strCharacterName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strDescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strMetatype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strMetavariant;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strQualities;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int intTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] bytFile;
        
        public UploadCharacterRequestBody() {
        }
        
        public UploadCharacterRequestBody(string strUserName, int intCharacterID, string strCharacterName, string strDescription, string strMetatype, string strMetavariant, string strQualities, int intTypeID, byte[] bytFile) {
            this.strUserName = strUserName;
            this.intCharacterID = intCharacterID;
            this.strCharacterName = strCharacterName;
            this.strDescription = strDescription;
            this.strMetatype = strMetatype;
            this.strMetavariant = strMetavariant;
            this.strQualities = strQualities;
            this.intTypeID = intTypeID;
            this.bytFile = bytFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadCharacterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadCharacterResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.UploadCharacterResponseBody Body;
        
        public UploadCharacterResponse() {
        }
        
        public UploadCharacterResponse(Chummer.OmaeService.UploadCharacterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class UploadCharacterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UploadCharacterResult;
        
        public UploadCharacterResponseBody() {
        }
        
        public UploadCharacterResponseBody(bool UploadCharacterResult) {
            this.UploadCharacterResult = UploadCharacterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadCharacter153Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadCharacter153", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.UploadCharacter153RequestBody Body;
        
        public UploadCharacter153Request() {
        }
        
        public UploadCharacter153Request(Chummer.OmaeService.UploadCharacter153RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class UploadCharacter153RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int intCharacterID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strCharacterName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strDescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strMetatype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strMetavariant;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strQualities;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int intTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int intCreated;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public byte[] bytFile;
        
        public UploadCharacter153RequestBody() {
        }
        
        public UploadCharacter153RequestBody(string strUserName, int intCharacterID, string strCharacterName, string strDescription, string strMetatype, string strMetavariant, string strQualities, int intTypeID, int intCreated, byte[] bytFile) {
            this.strUserName = strUserName;
            this.intCharacterID = intCharacterID;
            this.strCharacterName = strCharacterName;
            this.strDescription = strDescription;
            this.strMetatype = strMetatype;
            this.strMetavariant = strMetavariant;
            this.strQualities = strQualities;
            this.intTypeID = intTypeID;
            this.intCreated = intCreated;
            this.bytFile = bytFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadCharacter153Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadCharacter153Response", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.UploadCharacter153ResponseBody Body;
        
        public UploadCharacter153Response() {
        }
        
        public UploadCharacter153Response(Chummer.OmaeService.UploadCharacter153ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class UploadCharacter153ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UploadCharacter153Result;
        
        public UploadCharacter153ResponseBody() {
        }
        
        public UploadCharacter153ResponseBody(bool UploadCharacter153Result) {
            this.UploadCharacter153Result = UploadCharacter153Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadCharacterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadCharacter", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.DownloadCharacterRequestBody Body;
        
        public DownloadCharacterRequest() {
        }
        
        public DownloadCharacterRequest(Chummer.OmaeService.DownloadCharacterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class DownloadCharacterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intCharacterID;
        
        public DownloadCharacterRequestBody() {
        }
        
        public DownloadCharacterRequestBody(int intCharacterID) {
            this.intCharacterID = intCharacterID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadCharacterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadCharacterResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.DownloadCharacterResponseBody Body;
        
        public DownloadCharacterResponse() {
        }
        
        public DownloadCharacterResponse(Chummer.OmaeService.DownloadCharacterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class DownloadCharacterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownloadCharacterResult;
        
        public DownloadCharacterResponseBody() {
        }
        
        public DownloadCharacterResponseBody(byte[] DownloadCharacterResult) {
            this.DownloadCharacterResult = DownloadCharacterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchCharactersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchCharacters", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.FetchCharactersRequestBody Body;
        
        public FetchCharactersRequest() {
        }
        
        public FetchCharactersRequest(Chummer.OmaeService.FetchCharactersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class FetchCharactersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int intSortOrder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strMetatype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strMetavariant;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strQuality1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strQuality2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strQuality3;
        
        public FetchCharactersRequestBody() {
        }
        
        public FetchCharactersRequestBody(int intTypeID, int intSortOrder, string strMetatype, string strMetavariant, string strUser, string strQuality1, string strQuality2, string strQuality3) {
            this.intTypeID = intTypeID;
            this.intSortOrder = intSortOrder;
            this.strMetatype = strMetatype;
            this.strMetavariant = strMetavariant;
            this.strUser = strUser;
            this.strQuality1 = strQuality1;
            this.strQuality2 = strQuality2;
            this.strQuality3 = strQuality3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchCharactersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchCharactersResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.FetchCharactersResponseBody Body;
        
        public FetchCharactersResponse() {
        }
        
        public FetchCharactersResponse(Chummer.OmaeService.FetchCharactersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class FetchCharactersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement FetchCharactersResult;
        
        public FetchCharactersResponseBody() {
        }
        
        public FetchCharactersResponseBody(System.Xml.Linq.XElement FetchCharactersResult) {
            this.FetchCharactersResult = FetchCharactersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchCharacters153Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchCharacters153", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.FetchCharacters153RequestBody Body;
        
        public FetchCharacters153Request() {
        }
        
        public FetchCharacters153Request(Chummer.OmaeService.FetchCharacters153RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class FetchCharacters153RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int intSortOrder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strMetatype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strMetavariant;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int intCreated;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strQuality1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string strQuality2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string strQuality3;
        
        public FetchCharacters153RequestBody() {
        }
        
        public FetchCharacters153RequestBody(int intTypeID, int intSortOrder, string strMetatype, string strMetavariant, int intCreated, string strUser, string strQuality1, string strQuality2, string strQuality3) {
            this.intTypeID = intTypeID;
            this.intSortOrder = intSortOrder;
            this.strMetatype = strMetatype;
            this.strMetavariant = strMetavariant;
            this.intCreated = intCreated;
            this.strUser = strUser;
            this.strQuality1 = strQuality1;
            this.strQuality2 = strQuality2;
            this.strQuality3 = strQuality3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchCharacters153Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchCharacters153Response", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.FetchCharacters153ResponseBody Body;
        
        public FetchCharacters153Response() {
        }
        
        public FetchCharacters153Response(Chummer.OmaeService.FetchCharacters153ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class FetchCharacters153ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement FetchCharacters153Result;
        
        public FetchCharacters153ResponseBody() {
        }
        
        public FetchCharacters153ResponseBody(System.Xml.Linq.XElement FetchCharacters153Result) {
            this.FetchCharacters153Result = FetchCharacters153Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDataFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDataFile", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.UploadDataFileRequestBody Body;
        
        public UploadDataFileRequest() {
        }
        
        public UploadDataFileRequest(Chummer.OmaeService.UploadDataFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class UploadDataFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int intDataID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strDataName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strDescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strFilesIncluded;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] bytFile;
        
        public UploadDataFileRequestBody() {
        }
        
        public UploadDataFileRequestBody(string strUserName, int intDataID, string strDataName, string strDescription, string strFilesIncluded, byte[] bytFile) {
            this.strUserName = strUserName;
            this.intDataID = intDataID;
            this.strDataName = strDataName;
            this.strDescription = strDescription;
            this.strFilesIncluded = strFilesIncluded;
            this.bytFile = bytFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDataFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDataFileResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.UploadDataFileResponseBody Body;
        
        public UploadDataFileResponse() {
        }
        
        public UploadDataFileResponse(Chummer.OmaeService.UploadDataFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class UploadDataFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UploadDataFileResult;
        
        public UploadDataFileResponseBody() {
        }
        
        public UploadDataFileResponseBody(bool UploadDataFileResult) {
            this.UploadDataFileResult = UploadDataFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadDataFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadDataFile", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.DownloadDataFileRequestBody Body;
        
        public DownloadDataFileRequest() {
        }
        
        public DownloadDataFileRequest(Chummer.OmaeService.DownloadDataFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class DownloadDataFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intDataID;
        
        public DownloadDataFileRequestBody() {
        }
        
        public DownloadDataFileRequestBody(int intDataID) {
            this.intDataID = intDataID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadDataFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadDataFileResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.DownloadDataFileResponseBody Body;
        
        public DownloadDataFileResponse() {
        }
        
        public DownloadDataFileResponse(Chummer.OmaeService.DownloadDataFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class DownloadDataFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownloadDataFileResult;
        
        public DownloadDataFileResponseBody() {
        }
        
        public DownloadDataFileResponseBody(byte[] DownloadDataFileResult) {
            this.DownloadDataFileResult = DownloadDataFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchDataFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchDataFiles", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.FetchDataFilesRequestBody Body;
        
        public FetchDataFilesRequest() {
        }
        
        public FetchDataFilesRequest(Chummer.OmaeService.FetchDataFilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class FetchDataFilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intSortOrder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strFilesIncluded;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strUser;
        
        public FetchDataFilesRequestBody() {
        }
        
        public FetchDataFilesRequestBody(int intSortOrder, string strFilesIncluded, string strUser) {
            this.intSortOrder = intSortOrder;
            this.strFilesIncluded = strFilesIncluded;
            this.strUser = strUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchDataFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchDataFilesResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.FetchDataFilesResponseBody Body;
        
        public FetchDataFilesResponse() {
        }
        
        public FetchDataFilesResponse(Chummer.OmaeService.FetchDataFilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class FetchDataFilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement FetchDataFilesResult;
        
        public FetchDataFilesResponseBody() {
        }
        
        public FetchDataFilesResponseBody(System.Xml.Linq.XElement FetchDataFilesResult) {
            this.FetchDataFilesResult = FetchDataFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadSheetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadSheet", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.UploadSheetRequestBody Body;
        
        public UploadSheetRequest() {
        }
        
        public UploadSheetRequest(Chummer.OmaeService.UploadSheetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class UploadSheetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int intSheetID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strSheetName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strDescription;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] bytFile;
        
        public UploadSheetRequestBody() {
        }
        
        public UploadSheetRequestBody(string strUserName, int intSheetID, string strSheetName, string strDescription, byte[] bytFile) {
            this.strUserName = strUserName;
            this.intSheetID = intSheetID;
            this.strSheetName = strSheetName;
            this.strDescription = strDescription;
            this.bytFile = bytFile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadSheetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadSheetResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.UploadSheetResponseBody Body;
        
        public UploadSheetResponse() {
        }
        
        public UploadSheetResponse(Chummer.OmaeService.UploadSheetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class UploadSheetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UploadSheetResult;
        
        public UploadSheetResponseBody() {
        }
        
        public UploadSheetResponseBody(bool UploadSheetResult) {
            this.UploadSheetResult = UploadSheetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadSheetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadSheet", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.DownloadSheetRequestBody Body;
        
        public DownloadSheetRequest() {
        }
        
        public DownloadSheetRequest(Chummer.OmaeService.DownloadSheetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class DownloadSheetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intSheetID;
        
        public DownloadSheetRequestBody() {
        }
        
        public DownloadSheetRequestBody(int intSheetID) {
            this.intSheetID = intSheetID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadSheetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadSheetResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.DownloadSheetResponseBody Body;
        
        public DownloadSheetResponse() {
        }
        
        public DownloadSheetResponse(Chummer.OmaeService.DownloadSheetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class DownloadSheetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] DownloadSheetResult;
        
        public DownloadSheetResponseBody() {
        }
        
        public DownloadSheetResponseBody(byte[] DownloadSheetResult) {
            this.DownloadSheetResult = DownloadSheetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchSheetsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchSheets", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.FetchSheetsRequestBody Body;
        
        public FetchSheetsRequest() {
        }
        
        public FetchSheetsRequest(Chummer.OmaeService.FetchSheetsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class FetchSheetsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intSortOrder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strUser;
        
        public FetchSheetsRequestBody() {
        }
        
        public FetchSheetsRequestBody(int intSortOrder, string strUser) {
            this.intSortOrder = intSortOrder;
            this.strUser = strUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchSheetsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchSheetsResponse", Namespace="http://www.dndjunkie.com/", Order=0)]
        public Chummer.OmaeService.FetchSheetsResponseBody Body;
        
        public FetchSheetsResponse() {
        }
        
        public FetchSheetsResponse(Chummer.OmaeService.FetchSheetsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.dndjunkie.com/")]
    public partial class FetchSheetsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement FetchSheetsResult;
        
        public FetchSheetsResponseBody() {
        }
        
        public FetchSheetsResponseBody(System.Xml.Linq.XElement FetchSheetsResult) {
            this.FetchSheetsResult = FetchSheetsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface omaeSoapChannel : Chummer.OmaeService.omaeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class omaeSoapClient : System.ServiceModel.ClientBase<Chummer.OmaeService.omaeSoap>, Chummer.OmaeService.omaeSoap {
        
        public omaeSoapClient() {
        }
        
        public omaeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public omaeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public omaeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public omaeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.RegisterUserResponse Chummer.OmaeService.omaeSoap.RegisterUser(Chummer.OmaeService.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public int RegisterUser(string strUserName, string strPassword) {
            Chummer.OmaeService.RegisterUserRequest inValue = new Chummer.OmaeService.RegisterUserRequest();
            inValue.Body = new Chummer.OmaeService.RegisterUserRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            Chummer.OmaeService.RegisterUserResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).RegisterUser(inValue);
            return retVal.Body.RegisterUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.LoginResponse Chummer.OmaeService.omaeSoap.Login(Chummer.OmaeService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string strUserName, string strPassword) {
            Chummer.OmaeService.LoginRequest inValue = new Chummer.OmaeService.LoginRequest();
            inValue.Body = new Chummer.OmaeService.LoginRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.strPassword = strPassword;
            Chummer.OmaeService.LoginResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.SetEmailAddressResponse Chummer.OmaeService.omaeSoap.SetEmailAddress(Chummer.OmaeService.SetEmailAddressRequest request) {
            return base.Channel.SetEmailAddress(request);
        }
        
        public bool SetEmailAddress(string strUserName, string strEmail) {
            Chummer.OmaeService.SetEmailAddressRequest inValue = new Chummer.OmaeService.SetEmailAddressRequest();
            inValue.Body = new Chummer.OmaeService.SetEmailAddressRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.strEmail = strEmail;
            Chummer.OmaeService.SetEmailAddressResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).SetEmailAddress(inValue);
            return retVal.Body.SetEmailAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.GetEmailAddressResponse Chummer.OmaeService.omaeSoap.GetEmailAddress(Chummer.OmaeService.GetEmailAddressRequest request) {
            return base.Channel.GetEmailAddress(request);
        }
        
        public string GetEmailAddress(string strUserName) {
            Chummer.OmaeService.GetEmailAddressRequest inValue = new Chummer.OmaeService.GetEmailAddressRequest();
            inValue.Body = new Chummer.OmaeService.GetEmailAddressRequestBody();
            inValue.Body.strUserName = strUserName;
            Chummer.OmaeService.GetEmailAddressResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).GetEmailAddress(inValue);
            return retVal.Body.GetEmailAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.ResetPasswordResponse Chummer.OmaeService.omaeSoap.ResetPassword(Chummer.OmaeService.ResetPasswordRequest request) {
            return base.Channel.ResetPassword(request);
        }
        
        public bool ResetPassword(string strUserName) {
            Chummer.OmaeService.ResetPasswordRequest inValue = new Chummer.OmaeService.ResetPasswordRequest();
            inValue.Body = new Chummer.OmaeService.ResetPasswordRequestBody();
            inValue.Body.strUserName = strUserName;
            Chummer.OmaeService.ResetPasswordResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).ResetPassword(inValue);
            return retVal.Body.ResetPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.GetCharacterTypesResponse Chummer.OmaeService.omaeSoap.GetCharacterTypes(Chummer.OmaeService.GetCharacterTypesRequest request) {
            return base.Channel.GetCharacterTypes(request);
        }
        
        public System.Xml.Linq.XElement GetCharacterTypes() {
            Chummer.OmaeService.GetCharacterTypesRequest inValue = new Chummer.OmaeService.GetCharacterTypesRequest();
            inValue.Body = new Chummer.OmaeService.GetCharacterTypesRequestBody();
            Chummer.OmaeService.GetCharacterTypesResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).GetCharacterTypes(inValue);
            return retVal.Body.GetCharacterTypesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.UploadCharacterResponse Chummer.OmaeService.omaeSoap.UploadCharacter(Chummer.OmaeService.UploadCharacterRequest request) {
            return base.Channel.UploadCharacter(request);
        }
        
        public bool UploadCharacter(string strUserName, int intCharacterID, string strCharacterName, string strDescription, string strMetatype, string strMetavariant, string strQualities, int intTypeID, byte[] bytFile) {
            Chummer.OmaeService.UploadCharacterRequest inValue = new Chummer.OmaeService.UploadCharacterRequest();
            inValue.Body = new Chummer.OmaeService.UploadCharacterRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.intCharacterID = intCharacterID;
            inValue.Body.strCharacterName = strCharacterName;
            inValue.Body.strDescription = strDescription;
            inValue.Body.strMetatype = strMetatype;
            inValue.Body.strMetavariant = strMetavariant;
            inValue.Body.strQualities = strQualities;
            inValue.Body.intTypeID = intTypeID;
            inValue.Body.bytFile = bytFile;
            Chummer.OmaeService.UploadCharacterResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).UploadCharacter(inValue);
            return retVal.Body.UploadCharacterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.UploadCharacter153Response Chummer.OmaeService.omaeSoap.UploadCharacter153(Chummer.OmaeService.UploadCharacter153Request request) {
            return base.Channel.UploadCharacter153(request);
        }
        
        public bool UploadCharacter153(string strUserName, int intCharacterID, string strCharacterName, string strDescription, string strMetatype, string strMetavariant, string strQualities, int intTypeID, int intCreated, byte[] bytFile) {
            Chummer.OmaeService.UploadCharacter153Request inValue = new Chummer.OmaeService.UploadCharacter153Request();
            inValue.Body = new Chummer.OmaeService.UploadCharacter153RequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.intCharacterID = intCharacterID;
            inValue.Body.strCharacterName = strCharacterName;
            inValue.Body.strDescription = strDescription;
            inValue.Body.strMetatype = strMetatype;
            inValue.Body.strMetavariant = strMetavariant;
            inValue.Body.strQualities = strQualities;
            inValue.Body.intTypeID = intTypeID;
            inValue.Body.intCreated = intCreated;
            inValue.Body.bytFile = bytFile;
            Chummer.OmaeService.UploadCharacter153Response retVal = ((Chummer.OmaeService.omaeSoap)(this)).UploadCharacter153(inValue);
            return retVal.Body.UploadCharacter153Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.DownloadCharacterResponse Chummer.OmaeService.omaeSoap.DownloadCharacter(Chummer.OmaeService.DownloadCharacterRequest request) {
            return base.Channel.DownloadCharacter(request);
        }
        
        public byte[] DownloadCharacter(int intCharacterID) {
            Chummer.OmaeService.DownloadCharacterRequest inValue = new Chummer.OmaeService.DownloadCharacterRequest();
            inValue.Body = new Chummer.OmaeService.DownloadCharacterRequestBody();
            inValue.Body.intCharacterID = intCharacterID;
            Chummer.OmaeService.DownloadCharacterResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).DownloadCharacter(inValue);
            return retVal.Body.DownloadCharacterResult;
        }
        
        public bool DeleteCharacter(int intCharacterID) {
            return base.Channel.DeleteCharacter(intCharacterID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.FetchCharactersResponse Chummer.OmaeService.omaeSoap.FetchCharacters(Chummer.OmaeService.FetchCharactersRequest request) {
            return base.Channel.FetchCharacters(request);
        }
        
        public System.Xml.Linq.XElement FetchCharacters(int intTypeID, int intSortOrder, string strMetatype, string strMetavariant, string strUser, string strQuality1, string strQuality2, string strQuality3) {
            Chummer.OmaeService.FetchCharactersRequest inValue = new Chummer.OmaeService.FetchCharactersRequest();
            inValue.Body = new Chummer.OmaeService.FetchCharactersRequestBody();
            inValue.Body.intTypeID = intTypeID;
            inValue.Body.intSortOrder = intSortOrder;
            inValue.Body.strMetatype = strMetatype;
            inValue.Body.strMetavariant = strMetavariant;
            inValue.Body.strUser = strUser;
            inValue.Body.strQuality1 = strQuality1;
            inValue.Body.strQuality2 = strQuality2;
            inValue.Body.strQuality3 = strQuality3;
            Chummer.OmaeService.FetchCharactersResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).FetchCharacters(inValue);
            return retVal.Body.FetchCharactersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.FetchCharacters153Response Chummer.OmaeService.omaeSoap.FetchCharacters153(Chummer.OmaeService.FetchCharacters153Request request) {
            return base.Channel.FetchCharacters153(request);
        }
        
        public System.Xml.Linq.XElement FetchCharacters153(int intTypeID, int intSortOrder, string strMetatype, string strMetavariant, int intCreated, string strUser, string strQuality1, string strQuality2, string strQuality3) {
            Chummer.OmaeService.FetchCharacters153Request inValue = new Chummer.OmaeService.FetchCharacters153Request();
            inValue.Body = new Chummer.OmaeService.FetchCharacters153RequestBody();
            inValue.Body.intTypeID = intTypeID;
            inValue.Body.intSortOrder = intSortOrder;
            inValue.Body.strMetatype = strMetatype;
            inValue.Body.strMetavariant = strMetavariant;
            inValue.Body.intCreated = intCreated;
            inValue.Body.strUser = strUser;
            inValue.Body.strQuality1 = strQuality1;
            inValue.Body.strQuality2 = strQuality2;
            inValue.Body.strQuality3 = strQuality3;
            Chummer.OmaeService.FetchCharacters153Response retVal = ((Chummer.OmaeService.omaeSoap)(this)).FetchCharacters153(inValue);
            return retVal.Body.FetchCharacters153Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.UploadDataFileResponse Chummer.OmaeService.omaeSoap.UploadDataFile(Chummer.OmaeService.UploadDataFileRequest request) {
            return base.Channel.UploadDataFile(request);
        }
        
        public bool UploadDataFile(string strUserName, int intDataID, string strDataName, string strDescription, string strFilesIncluded, byte[] bytFile) {
            Chummer.OmaeService.UploadDataFileRequest inValue = new Chummer.OmaeService.UploadDataFileRequest();
            inValue.Body = new Chummer.OmaeService.UploadDataFileRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.intDataID = intDataID;
            inValue.Body.strDataName = strDataName;
            inValue.Body.strDescription = strDescription;
            inValue.Body.strFilesIncluded = strFilesIncluded;
            inValue.Body.bytFile = bytFile;
            Chummer.OmaeService.UploadDataFileResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).UploadDataFile(inValue);
            return retVal.Body.UploadDataFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.DownloadDataFileResponse Chummer.OmaeService.omaeSoap.DownloadDataFile(Chummer.OmaeService.DownloadDataFileRequest request) {
            return base.Channel.DownloadDataFile(request);
        }
        
        public byte[] DownloadDataFile(int intDataID) {
            Chummer.OmaeService.DownloadDataFileRequest inValue = new Chummer.OmaeService.DownloadDataFileRequest();
            inValue.Body = new Chummer.OmaeService.DownloadDataFileRequestBody();
            inValue.Body.intDataID = intDataID;
            Chummer.OmaeService.DownloadDataFileResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).DownloadDataFile(inValue);
            return retVal.Body.DownloadDataFileResult;
        }
        
        public bool DeleteDataFile(int intDataID) {
            return base.Channel.DeleteDataFile(intDataID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.FetchDataFilesResponse Chummer.OmaeService.omaeSoap.FetchDataFiles(Chummer.OmaeService.FetchDataFilesRequest request) {
            return base.Channel.FetchDataFiles(request);
        }
        
        public System.Xml.Linq.XElement FetchDataFiles(int intSortOrder, string strFilesIncluded, string strUser) {
            Chummer.OmaeService.FetchDataFilesRequest inValue = new Chummer.OmaeService.FetchDataFilesRequest();
            inValue.Body = new Chummer.OmaeService.FetchDataFilesRequestBody();
            inValue.Body.intSortOrder = intSortOrder;
            inValue.Body.strFilesIncluded = strFilesIncluded;
            inValue.Body.strUser = strUser;
            Chummer.OmaeService.FetchDataFilesResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).FetchDataFiles(inValue);
            return retVal.Body.FetchDataFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.UploadSheetResponse Chummer.OmaeService.omaeSoap.UploadSheet(Chummer.OmaeService.UploadSheetRequest request) {
            return base.Channel.UploadSheet(request);
        }
        
        public bool UploadSheet(string strUserName, int intSheetID, string strSheetName, string strDescription, byte[] bytFile) {
            Chummer.OmaeService.UploadSheetRequest inValue = new Chummer.OmaeService.UploadSheetRequest();
            inValue.Body = new Chummer.OmaeService.UploadSheetRequestBody();
            inValue.Body.strUserName = strUserName;
            inValue.Body.intSheetID = intSheetID;
            inValue.Body.strSheetName = strSheetName;
            inValue.Body.strDescription = strDescription;
            inValue.Body.bytFile = bytFile;
            Chummer.OmaeService.UploadSheetResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).UploadSheet(inValue);
            return retVal.Body.UploadSheetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.DownloadSheetResponse Chummer.OmaeService.omaeSoap.DownloadSheet(Chummer.OmaeService.DownloadSheetRequest request) {
            return base.Channel.DownloadSheet(request);
        }
        
        public byte[] DownloadSheet(int intSheetID) {
            Chummer.OmaeService.DownloadSheetRequest inValue = new Chummer.OmaeService.DownloadSheetRequest();
            inValue.Body = new Chummer.OmaeService.DownloadSheetRequestBody();
            inValue.Body.intSheetID = intSheetID;
            Chummer.OmaeService.DownloadSheetResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).DownloadSheet(inValue);
            return retVal.Body.DownloadSheetResult;
        }
        
        public bool DeleteSheet(int intSheetID) {
            return base.Channel.DeleteSheet(intSheetID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Chummer.OmaeService.FetchSheetsResponse Chummer.OmaeService.omaeSoap.FetchSheets(Chummer.OmaeService.FetchSheetsRequest request) {
            return base.Channel.FetchSheets(request);
        }
        
        public System.Xml.Linq.XElement FetchSheets(int intSortOrder, string strUser) {
            Chummer.OmaeService.FetchSheetsRequest inValue = new Chummer.OmaeService.FetchSheetsRequest();
            inValue.Body = new Chummer.OmaeService.FetchSheetsRequestBody();
            inValue.Body.intSortOrder = intSortOrder;
            inValue.Body.strUser = strUser;
            Chummer.OmaeService.FetchSheetsResponse retVal = ((Chummer.OmaeService.omaeSoap)(this)).FetchSheets(inValue);
            return retVal.Body.FetchSheetsResult;
        }
    }
}
