// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SINners.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ChummerUploadClient
    {
        /// <summary>
        /// Initializes a new instance of the ChummerUploadClient class.
        /// </summary>
        public ChummerUploadClient() { }

        /// <summary>
        /// Initializes a new instance of the ChummerUploadClient class.
        /// </summary>
        public ChummerUploadClient(Guid? uploadClientId = default(Guid?), string chummerVersion = default(string), string clientSecret = default(string), string userEmail = default(string))
        {
            UploadClientId = uploadClientId;
            ChummerVersion = chummerVersion;
            ClientSecret = clientSecret;
            UserEmail = userEmail;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uploadClientId")]
        public Guid? UploadClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chummerVersion")]
        public string ChummerVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientSecret")]
        public string ClientSecret { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userEmail")]
        public string UserEmail { get; set; }

    }
}
