// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SINners.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ResultAccountGetSinnersByAuthorization
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ResultAccountGetSinnersByAuthorization class.
        /// </summary>
        public ResultAccountGetSinnersByAuthorization()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// ResultAccountGetSinnersByAuthorization class.
        /// </summary>
        public ResultAccountGetSinnersByAuthorization(SINSearchGroupResult mySINSearchGroupResult = default(SINSearchGroupResult), object myException = default(object), bool? callSuccess = default(bool?), string errorText = default(string))
        {
            MySINSearchGroupResult = mySINSearchGroupResult;
            MyException = myException;
            CallSuccess = callSuccess;
            ErrorText = errorText;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mySINSearchGroupResult")]
        public SINSearchGroupResult MySINSearchGroupResult { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "myException")]
        public object MyException { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "callSuccess")]
        public bool? CallSuccess { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorText")]
        public string ErrorText { get; set; }

    }
}
