// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SINners.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ResultAccountGetRoles
    {
        /// <summary>
        /// Initializes a new instance of the ResultAccountGetRoles class.
        /// </summary>
        public ResultAccountGetRoles() { }

        /// <summary>
        /// Initializes a new instance of the ResultAccountGetRoles class.
        /// </summary>
        public ResultAccountGetRoles(IList<string> roles = default(IList<string>), IList<string> possibleRoles = default(IList<string>), object myException = default(object), bool? callSuccess = default(bool?), string errorText = default(string))
        {
            Roles = roles;
            PossibleRoles = possibleRoles;
            MyException = myException;
            CallSuccess = callSuccess;
            ErrorText = errorText;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "roles")]
        public IList<string> Roles { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "possibleRoles")]
        public IList<string> PossibleRoles { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "myException")]
        public object MyException { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "callSuccess")]
        public bool? CallSuccess { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorText")]
        public string ErrorText { get; set; }

    }
}
