// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SINners.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SearchTag
    {
        /// <summary>
        /// Initializes a new instance of the SearchTag class.
        /// </summary>
        public SearchTag() { }

        /// <summary>
        /// Initializes a new instance of the SearchTag class.
        /// </summary>
        public SearchTag(string sTagName = default(string), string sTagValue = default(string), IList<SearchTag> sTags = default(IList<SearchTag>), string sSearchOpterator = default(string))
        {
            STagName = sTagName;
            STagValue = sTagValue;
            STags = sTags;
            SSearchOpterator = sSearchOpterator;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sTagName")]
        public string STagName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sTagValue")]
        public string STagValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sTags")]
        public IList<SearchTag> STags { get; set; }

        /// <summary>
        /// Possible values include: 'bigger', 'smaller', 'equal', 'contains',
        /// 'notnull'
        /// </summary>
        [JsonProperty(PropertyName = "sSearchOpterator")]
        public string SSearchOpterator { get; set; }

    }
}
