// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SINners.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SINnerVisibility
    {
        /// <summary>
        /// Initializes a new instance of the SINnerVisibility class.
        /// </summary>
        public SINnerVisibility()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SINnerVisibility class.
        /// </summary>
        public SINnerVisibility(System.Guid? id = default(System.Guid?), bool? isPublic = default(bool?), bool? isGroupVisible = default(bool?), IList<SINnerUserRight> userRights = default(IList<SINnerUserRight>))
        {
            Id = id;
            IsPublic = isPublic;
            IsGroupVisible = isGroupVisible;
            UserRights = userRights;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isPublic")]
        public bool? IsPublic { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isGroupVisible")]
        public bool? IsGroupVisible { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userRights")]
        public IList<SINnerUserRight> UserRights { get; set; }

    }
}
