// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SINners.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SINner
    {
        /// <summary>
        /// Initializes a new instance of the SINner class.
        /// </summary>
        public SINner() { }

        /// <summary>
        /// Initializes a new instance of the SINner class.
        /// </summary>
        public SINner(Guid? siNnerId = default(Guid?), string downloadUrl = default(string), DateTime? uploadDateTime = default(DateTime?), ChummerUploadClient chummerUploadClient = default(ChummerUploadClient), SINnerMetaData siNnerMetaData = default(SINnerMetaData), string googleDriveFileId = default(string))
        {
            SiNnerId = siNnerId;
            DownloadUrl = downloadUrl;
            UploadDateTime = uploadDateTime;
            ChummerUploadClient = chummerUploadClient;
            SiNnerMetaData = siNnerMetaData;
            GoogleDriveFileId = googleDriveFileId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "siNnerId")]
        public Guid? SiNnerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "downloadUrl")]
        public string DownloadUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uploadDateTime")]
        public DateTime? UploadDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chummerUploadClient")]
        public ChummerUploadClient ChummerUploadClient { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "siNnerMetaData")]
        public SINnerMetaData SiNnerMetaData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "googleDriveFileId")]
        public string GoogleDriveFileId { get; set; }

    }
}
