// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SINners.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SINnerMetaData
    {
        /// <summary>
        /// Initializes a new instance of the SINnerMetaData class.
        /// </summary>
        public SINnerMetaData() { }

        /// <summary>
        /// Initializes a new instance of the SINnerMetaData class.
        /// </summary>
        public SINnerMetaData(Guid? siNnerMetaDataId = default(Guid?), IList<Tag> tags = default(IList<Tag>))
        {
            SiNnerMetaDataId = siNnerMetaDataId;
            Tags = tags;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "siNnerMetaDataId")]
        public Guid? SiNnerMetaDataId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tags")]
        public IList<Tag> Tags { get; set; }

    }
}
