// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SINners.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SINnerGroupSetting
    {
        /// <summary>
        /// Initializes a new instance of the SINnerGroupSetting class.
        /// </summary>
        public SINnerGroupSetting()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SINnerGroupSetting class.
        /// </summary>
        public SINnerGroupSetting(System.Guid? id = default(System.Guid?), System.Guid? myGroupId = default(System.Guid?), string downloadUrl = default(string), System.DateTime? uploadDateTime = default(System.DateTime?), System.DateTime? lastChange = default(System.DateTime?), string fileName = default(string))
        {
            Id = id;
            MyGroupId = myGroupId;
            DownloadUrl = downloadUrl;
            UploadDateTime = uploadDateTime;
            LastChange = lastChange;
            FileName = fileName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "myGroupId")]
        public System.Guid? MyGroupId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "downloadUrl")]
        public string DownloadUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "uploadDateTime")]
        public System.DateTime? UploadDateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastChange")]
        public System.DateTime? LastChange { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; private set; }

    }
}
