// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SINners.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SINnerSearchGroupMember
    {
        /// <summary>
        /// Initializes a new instance of the SINnerSearchGroupMember class.
        /// </summary>
        public SINnerSearchGroupMember()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SINnerSearchGroupMember class.
        /// </summary>
        public SINnerSearchGroupMember(SINner mySINner = default(SINner), string username = default(string), bool? isFavorite = default(bool?))
        {
            MySINner = mySINner;
            Username = username;
            IsFavorite = isFavorite;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mySINner")]
        public SINner MySINner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isFavorite")]
        public bool? IsFavorite { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (MySINner != null)
            {
                MySINner.Validate();
            }
        }
    }
}
