// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SINners.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SINnersList
    {
        /// <summary>
        /// Initializes a new instance of the SINnersList class.
        /// </summary>
        public SINnersList() { }

        /// <summary>
        /// Initializes a new instance of the SINnersList class.
        /// </summary>
        public SINnersList(string header = default(string), IList<SINner> siNners = default(IList<SINner>), IList<SINnersList> sinList = default(IList<SINnersList>))
        {
            Header = header;
            SiNners = siNners;
            SinList = sinList;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "header")]
        public string Header { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "siNners")]
        public IList<SINner> SiNners { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sinList")]
        public IList<SINnersList> SinList { get; set; }

    }
}
