// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace SINners.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class UploadClient
    {
        /// <summary>
        /// Initializes a new instance of the UploadClient class.
        /// </summary>
        public UploadClient() { }

        /// <summary>
        /// Initializes a new instance of the UploadClient class.
        /// </summary>
        public UploadClient(Guid? id = default(Guid?), string chummerVersion = default(string), Guid? installationId = default(Guid?), string clientSecret = default(string), string userEmail = default(string))
        {
            Id = id;
            ChummerVersion = chummerVersion;
            InstallationId = installationId;
            ClientSecret = clientSecret;
            UserEmail = userEmail;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chummerVersion")]
        public string ChummerVersion { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "installationId")]
        public Guid? InstallationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientSecret")]
        public string ClientSecret { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userEmail")]
        public string UserEmail { get; set; }

    }
}
