// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SINners.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ChummerHubVersion
    {
        /// <summary>
        /// Initializes a new instance of the ChummerHubVersion class.
        /// </summary>
        public ChummerHubVersion()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ChummerHubVersion class.
        /// </summary>
        public ChummerHubVersion(string assemblyVersion = default(string))
        {
            AssemblyVersion = assemblyVersion;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "assemblyVersion")]
        public string AssemblyVersion { get; set; }

    }
}
