// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SINners.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ResultSinnerGetSINById
    {
        /// <summary>
        /// Initializes a new instance of the ResultSinnerGetSINById class.
        /// </summary>
        public ResultSinnerGetSINById()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResultSinnerGetSINById class.
        /// </summary>
        public ResultSinnerGetSINById(SINner mySINner = default(SINner), object myException = default(object), bool? callSuccess = default(bool?), string errorText = default(string))
        {
            MySINner = mySINner;
            MyException = myException;
            CallSuccess = callSuccess;
            ErrorText = errorText;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mySINner")]
        public SINner MySINner { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "myException")]
        public object MyException { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "callSuccess")]
        public bool? CallSuccess { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorText")]
        public string ErrorText { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (MySINner != null)
            {
                MySINner.Validate();
            }
        }
    }
}
